import { AttributeType } from "@/models/attribute/AttributeType";
import { AttributeOption } from "@/models/attribute/AttributeOption";

export type Attribute = {
  createdAt: string,
  updatedAt: string,
  createdBy: string | null,
  updatedBy: string | null,
  version: number,
  id: string,
  companyId: string,
  groupId: string,
  name: string,
  type: AttributeType,
  sortOrder: number,
  decScale: number | null,
  dateHideYear: boolean | null,
  system: boolean,
  unique: boolean,
  options?: AttributeOption[],
  required?: boolean,
  description?: string | null,
  defaultValue?: string | null,
  minValue?: number | null,
  maxValue?: number | null,
  onlyPositive?: boolean,
  minLength?: number | null,
  maxLength?: number | null,
  regex?: string | null,
  minDate?: string | null,
  maxDate?: string | null,
  minSelect?: number | null,
  maxSelect?: number | null,
}
