// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/dashboard" | "/desact" | "/desact/[page]" | "/login" | "/organization/people" | "/organization/people/[id]" | "/organization/people/[id]/documents" | "/organization/people/[id]/personal" | "/organization/people/[id]/time-off" | "/pricing" | "/products" | "/settings" | "/settings/account" | "/settings/general/company" | "/settings/general/customisation" | "/settings/general/dashboard" | "/settings/general/departments" | "/settings/general/export" | "/settings/general/import" | "/settings/general/job-catalog" | "/settings/general/job-levels" | "/settings/general/legal-entities" | "/settings/general/offices" | "/settings/general/teams" | "/settings/people/attributes" | "/settings/people/roles" | "/settings/people/roles/[id]" | "/solutions" | "/trial" | "/trial/confirm"
type AppRouteHandlerRoutes = "/api/auth/login" | "/api/auth/logout" | "/api/auth/register" | "/api/auth/register/confirm" | "/api/documents/[documentId]/delete" | "/api/documents/[documentId]/download" | "/api/documents/[documentId]/star" | "/api/documents/users/[userId]" | "/api/documents/users/[userId]/folders" | "/api/documents/users/[userId]/folders/[folderId]" | "/api/documents/users/[userId]/folders/[folderId]/content" | "/api/documents/users/[userId]/folders/[folderId]/delete" | "/api/documents/users/[userId]/folders/root" | "/api/documents/users/[userId]/upload" | "/api/groups" | "/api/health" | "/api/job-family" | "/api/legal-entity" | "/api/me/permissions" | "/api/office" | "/api/roles" | "/api/roles/[id]/permissions/modules" | "/api/users" | "/api/users/[id]" | "/api/users/[id]/roles" | "/api/users/[id]/roles/[roleId]" | "/api/users/routes/usersRoutes" | "/api/users/routes/usersRoutes/fields" | "/api/users/search"
type PageRoutes = never
type LayoutRoutes = "/" | "/organization/people/[id]" | "/settings/general"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/register": {}
  "/api/auth/register/confirm": {}
  "/api/documents/[documentId]/delete": { "documentId": string; }
  "/api/documents/[documentId]/download": { "documentId": string; }
  "/api/documents/[documentId]/star": { "documentId": string; }
  "/api/documents/users/[userId]": { "userId": string; }
  "/api/documents/users/[userId]/folders": { "userId": string; }
  "/api/documents/users/[userId]/folders/[folderId]": { "userId": string; "folderId": string; }
  "/api/documents/users/[userId]/folders/[folderId]/content": { "userId": string; "folderId": string; }
  "/api/documents/users/[userId]/folders/[folderId]/delete": { "userId": string; "folderId": string; }
  "/api/documents/users/[userId]/folders/root": { "userId": string; }
  "/api/documents/users/[userId]/upload": { "userId": string; }
  "/api/groups": {}
  "/api/health": {}
  "/api/job-family": {}
  "/api/legal-entity": {}
  "/api/me/permissions": {}
  "/api/office": {}
  "/api/roles": {}
  "/api/roles/[id]/permissions/modules": { "id": string; }
  "/api/users": {}
  "/api/users/[id]": { "id": string; }
  "/api/users/[id]/roles": { "id": string; }
  "/api/users/[id]/roles/[roleId]": { "id": string; "roleId": string; }
  "/api/users/routes/usersRoutes": {}
  "/api/users/routes/usersRoutes/fields": {}
  "/api/users/search": {}
  "/dashboard": {}
  "/desact": {}
  "/desact/[page]": { "page": string; }
  "/login": {}
  "/organization/people": {}
  "/organization/people/[id]": { "id": string; }
  "/organization/people/[id]/documents": { "id": string; }
  "/organization/people/[id]/personal": { "id": string; }
  "/organization/people/[id]/time-off": { "id": string; }
  "/pricing": {}
  "/products": {}
  "/settings": {}
  "/settings/account": {}
  "/settings/general": {}
  "/settings/general/company": {}
  "/settings/general/customisation": {}
  "/settings/general/dashboard": {}
  "/settings/general/departments": {}
  "/settings/general/export": {}
  "/settings/general/import": {}
  "/settings/general/job-catalog": {}
  "/settings/general/job-levels": {}
  "/settings/general/legal-entities": {}
  "/settings/general/offices": {}
  "/settings/general/teams": {}
  "/settings/people/attributes": {}
  "/settings/people/roles": {}
  "/settings/people/roles/[id]": { "id": string; }
  "/solutions": {}
  "/trial": {}
  "/trial/confirm": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/organization/people/[id]": never
  "/settings/general": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
