// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/dist/lib/metadata/types/metadata-interface.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
}


// Validate ..\..\app\(app)\dashboard\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\dashboard\\page.js")
  handler satisfies AppPageConfig<"/dashboard">
}

// Validate ..\..\app\(app)\organization\people\[id]\(tabs)\documents\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\organization\\people\\[id]\\(tabs)\\documents\\page.js")
  handler satisfies AppPageConfig<"/organization/people/[id]/documents">
}

// Validate ..\..\app\(app)\organization\people\[id]\(tabs)\personal\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\organization\\people\\[id]\\(tabs)\\personal\\page.js")
  handler satisfies AppPageConfig<"/organization/people/[id]/personal">
}

// Validate ..\..\app\(app)\organization\people\[id]\(tabs)\time-off\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\organization\\people\\[id]\\(tabs)\\time-off\\page.js")
  handler satisfies AppPageConfig<"/organization/people/[id]/time-off">
}

// Validate ..\..\app\(app)\organization\people\[id]\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\organization\\people\\[id]\\page.js")
  handler satisfies AppPageConfig<"/organization/people/[id]">
}

// Validate ..\..\app\(app)\organization\people\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\organization\\people\\page.js")
  handler satisfies AppPageConfig<"/organization/people">
}

// Validate ..\..\app\(app)\settings\account\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\account\\page.js")
  handler satisfies AppPageConfig<"/settings/account">
}

// Validate ..\..\app\(app)\settings\general\(departments-teams)\departments\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\general\\(departments-teams)\\departments\\page.js")
  handler satisfies AppPageConfig<"/settings/general/departments">
}

// Validate ..\..\app\(app)\settings\general\(departments-teams)\teams\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\general\\(departments-teams)\\teams\\page.js")
  handler satisfies AppPageConfig<"/settings/general/teams">
}

// Validate ..\..\app\(app)\settings\general\(import-export)\export\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\general\\(import-export)\\export\\page.js")
  handler satisfies AppPageConfig<"/settings/general/export">
}

// Validate ..\..\app\(app)\settings\general\(import-export)\import\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\general\\(import-export)\\import\\page.js")
  handler satisfies AppPageConfig<"/settings/general/import">
}

// Validate ..\..\app\(app)\settings\general\(job-catalog)\job-catalog\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\general\\(job-catalog)\\job-catalog\\page.js")
  handler satisfies AppPageConfig<"/settings/general/job-catalog">
}

// Validate ..\..\app\(app)\settings\general\(job-catalog)\job-levels\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\general\\(job-catalog)\\job-levels\\page.js")
  handler satisfies AppPageConfig<"/settings/general/job-levels">
}

// Validate ..\..\app\(app)\settings\general\(legal-entities-offices)\legal-entities\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\general\\(legal-entities-offices)\\legal-entities\\page.js")
  handler satisfies AppPageConfig<"/settings/general/legal-entities">
}

// Validate ..\..\app\(app)\settings\general\(legal-entities-offices)\offices\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\general\\(legal-entities-offices)\\offices\\page.js")
  handler satisfies AppPageConfig<"/settings/general/offices">
}

// Validate ..\..\app\(app)\settings\general\company\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\general\\company\\page.js")
  handler satisfies AppPageConfig<"/settings/general/company">
}

// Validate ..\..\app\(app)\settings\general\customisation\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\general\\customisation\\page.js")
  handler satisfies AppPageConfig<"/settings/general/customisation">
}

// Validate ..\..\app\(app)\settings\general\dashboard\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\general\\dashboard\\page.js")
  handler satisfies AppPageConfig<"/settings/general/dashboard">
}

// Validate ..\..\app\(app)\settings\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\page.js")
  handler satisfies AppPageConfig<"/settings">
}

// Validate ..\..\app\(app)\settings\people\attributes\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\people\\attributes\\page.js")
  handler satisfies AppPageConfig<"/settings/people/attributes">
}

// Validate ..\..\app\(app)\settings\people\roles\[id]\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\people\\roles\\[id]\\page.js")
  handler satisfies AppPageConfig<"/settings/people/roles/[id]">
}

// Validate ..\..\app\(app)\settings\people\roles\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\people\\roles\\page.js")
  handler satisfies AppPageConfig<"/settings/people/roles">
}

// Validate ..\..\app\(public)\about\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(public)\\about\\page.js")
  handler satisfies AppPageConfig<"/about">
}

// Validate ..\..\app\(public)\desact\[page]\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(public)\\desact\\[page]\\page.js")
  handler satisfies AppPageConfig<"/desact/[page]">
}

// Validate ..\..\app\(public)\desact\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(public)\\desact\\page.js")
  handler satisfies AppPageConfig<"/desact">
}

// Validate ..\..\app\(public)\login\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(public)\\login\\page.js")
  handler satisfies AppPageConfig<"/login">
}

// Validate ..\..\app\(public)\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(public)\\page.js")
  handler satisfies AppPageConfig<"/">
}

// Validate ..\..\app\(public)\pricing\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(public)\\pricing\\page.js")
  handler satisfies AppPageConfig<"/pricing">
}

// Validate ..\..\app\(public)\products\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(public)\\products\\page.js")
  handler satisfies AppPageConfig<"/products">
}

// Validate ..\..\app\(public)\solutions\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(public)\\solutions\\page.js")
  handler satisfies AppPageConfig<"/solutions">
}

// Validate ..\..\app\(public)\trial\confirm\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(public)\\trial\\confirm\\page.js")
  handler satisfies AppPageConfig<"/trial/confirm">
}

// Validate ..\..\app\(public)\trial\page.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(public)\\trial\\page.js")
  handler satisfies AppPageConfig<"/trial">
}

// Validate ..\..\app\api\auth\login\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\auth\\login\\route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/login">
}

// Validate ..\..\app\api\auth\logout\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\auth\\logout\\route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/logout">
}

// Validate ..\..\app\api\auth\register\confirm\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\auth\\register\\confirm\\route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/register/confirm">
}

// Validate ..\..\app\api\auth\register\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\auth\\register\\route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/register">
}

// Validate ..\..\app\api\documents\[documentId]\delete\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\documents\\[documentId]\\delete\\route.js")
  handler satisfies RouteHandlerConfig<"/api/documents/[documentId]/delete">
}

// Validate ..\..\app\api\documents\[documentId]\download\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\documents\\[documentId]\\download\\route.js")
  handler satisfies RouteHandlerConfig<"/api/documents/[documentId]/download">
}

// Validate ..\..\app\api\documents\[documentId]\star\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\documents\\[documentId]\\star\\route.js")
  handler satisfies RouteHandlerConfig<"/api/documents/[documentId]/star">
}

// Validate ..\..\app\api\documents\users\[userId]\folders\[folderId]\content\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\documents\\users\\[userId]\\folders\\[folderId]\\content\\route.js")
  handler satisfies RouteHandlerConfig<"/api/documents/users/[userId]/folders/[folderId]/content">
}

// Validate ..\..\app\api\documents\users\[userId]\folders\[folderId]\delete\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\documents\\users\\[userId]\\folders\\[folderId]\\delete\\route.js")
  handler satisfies RouteHandlerConfig<"/api/documents/users/[userId]/folders/[folderId]/delete">
}

// Validate ..\..\app\api\documents\users\[userId]\folders\[folderId]\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\documents\\users\\[userId]\\folders\\[folderId]\\route.js")
  handler satisfies RouteHandlerConfig<"/api/documents/users/[userId]/folders/[folderId]">
}

// Validate ..\..\app\api\documents\users\[userId]\folders\root\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\documents\\users\\[userId]\\folders\\root\\route.js")
  handler satisfies RouteHandlerConfig<"/api/documents/users/[userId]/folders/root">
}

// Validate ..\..\app\api\documents\users\[userId]\folders\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\documents\\users\\[userId]\\folders\\route.js")
  handler satisfies RouteHandlerConfig<"/api/documents/users/[userId]/folders">
}

// Validate ..\..\app\api\documents\users\[userId]\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\documents\\users\\[userId]\\route.js")
  handler satisfies RouteHandlerConfig<"/api/documents/users/[userId]">
}

// Validate ..\..\app\api\documents\users\[userId]\upload\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\documents\\users\\[userId]\\upload\\route.js")
  handler satisfies RouteHandlerConfig<"/api/documents/users/[userId]/upload">
}

// Validate ..\..\app\api\groups\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\groups\\route.js")
  handler satisfies RouteHandlerConfig<"/api/groups">
}

// Validate ..\..\app\api\health\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\health\\route.js")
  handler satisfies RouteHandlerConfig<"/api/health">
}

// Validate ..\..\app\api\job-family\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\job-family\\route.js")
  handler satisfies RouteHandlerConfig<"/api/job-family">
}

// Validate ..\..\app\api\legal-entity\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\legal-entity\\route.js")
  handler satisfies RouteHandlerConfig<"/api/legal-entity">
}

// Validate ..\..\app\api\me\permissions\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\me\\permissions\\route.js")
  handler satisfies RouteHandlerConfig<"/api/me/permissions">
}

// Validate ..\..\app\api\office\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\office\\route.js")
  handler satisfies RouteHandlerConfig<"/api/office">
}

// Validate ..\..\app\api\roles\[id]\permissions\modules\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\roles\\[id]\\permissions\\modules\\route.js")
  handler satisfies RouteHandlerConfig<"/api/roles/[id]/permissions/modules">
}

// Validate ..\..\app\api\roles\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\roles\\route.js")
  handler satisfies RouteHandlerConfig<"/api/roles">
}

// Validate ..\..\app\api\users\[id]\roles\[roleId]\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\users\\[id]\\roles\\[roleId]\\route.js")
  handler satisfies RouteHandlerConfig<"/api/users/[id]/roles/[roleId]">
}

// Validate ..\..\app\api\users\[id]\roles\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\users\\[id]\\roles\\route.js")
  handler satisfies RouteHandlerConfig<"/api/users/[id]/roles">
}

// Validate ..\..\app\api\users\[id]\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\users\\[id]\\route.js")
  handler satisfies RouteHandlerConfig<"/api/users/[id]">
}

// Validate ..\..\app\api\users\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\users\\route.js")
  handler satisfies RouteHandlerConfig<"/api/users">
}

// Validate ..\..\app\api\users\routes\usersRoutes\fields\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\users\\routes\\usersRoutes\\fields\\route.js")
  handler satisfies RouteHandlerConfig<"/api/users/routes/usersRoutes/fields">
}

// Validate ..\..\app\api\users\routes\usersRoutes\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\users\\routes\\usersRoutes\\route.js")
  handler satisfies RouteHandlerConfig<"/api/users/routes/usersRoutes">
}

// Validate ..\..\app\api\users\search\route.ts
{
  const handler = {} as typeof import("..\\..\\app\\api\\users\\search\\route.js")
  handler satisfies RouteHandlerConfig<"/api/users/search">
}





// Validate ..\..\app\(app)\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\layout.js")
  handler satisfies LayoutConfig<"/">
}

// Validate ..\..\app\(app)\organization\people\[id]\(tabs)\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\organization\\people\\[id]\\(tabs)\\layout.js")
  handler satisfies LayoutConfig<"/organization/people/[id]">
}

// Validate ..\..\app\(app)\settings\general\(departments-teams)\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\general\\(departments-teams)\\layout.js")
  handler satisfies LayoutConfig<"/settings/general">
}

// Validate ..\..\app\(app)\settings\general\(import-export)\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\general\\(import-export)\\layout.js")
  handler satisfies LayoutConfig<"/settings/general">
}

// Validate ..\..\app\(app)\settings\general\(job-catalog)\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\general\\(job-catalog)\\layout.js")
  handler satisfies LayoutConfig<"/settings/general">
}

// Validate ..\..\app\(app)\settings\general\(legal-entities-offices)\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(app)\\settings\\general\\(legal-entities-offices)\\layout.js")
  handler satisfies LayoutConfig<"/settings/general">
}

// Validate ..\..\app\(public)\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\(public)\\layout.js")
  handler satisfies LayoutConfig<"/">
}

// Validate ..\..\app\layout.tsx
{
  const handler = {} as typeof import("..\\..\\app\\layout.js")
  handler satisfies LayoutConfig<"/">
}
