import { AttributeOption, AttributeType } from "@/models/attribute";

export type CreateAttributeRequest = {
  name: string,
  groupId: string,
  type: AttributeType,
  isUnique: boolean,
  sensitive?: boolean,
  decScale: number | null,
  hideYear: boolean,
  options?: AttributeOption[],
  required?: boolean,
  description?: string | null,
  defaultValue?: string | null,
  minValue?: number | null,
  maxValue?: number | null,
  onlyPositive?: boolean,
  minLength?: number | null,
  maxLength?: number | null,
  regex?: string | null,
  minDate?: string | null,
  maxDate?: string | null,
  minSelect?: number | null,
  maxSelect?: number | null,
  objectFields?: string | null,
};
